from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


class RequirementStatus(str, Enum):
    """
    Status of an information requirement during the collection process.
    - UNKNOWN: Information not yet collected or evaluated.
    - KNOWN: Information has been provided and stored.
    - UNAVAILABLE: Applicable, but the answer isn't known or decided yet (e.g., "we don't have a fixed budget yet").
    - NOT_RELEVANT: Not applicable to this specific business at all (e.g., "pricing model" does not apply to a donation-based non-profit).
    """
    UNKNOWN = "UNKNOWN"
    KNOWN = "KNOWN"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_RELEVANT = "NOT_RELEVANT"


class InformationRequirement(BaseModel):
    """
    Represents a single piece of marketing information required or evaluated by the agent.
    Industry-agnostic schema supporting both predefined base framework items and dynamically discovered requirements.
    """
    id: str = Field(
        ...,
        description="Short unique string identifier for the requirement (e.g., 'pricing_model')."
    )
    title: str = Field(
        ...,
        description="Short human-readable title of the requirement (e.g., 'Pricing Model')."
    )
    description: str = Field(
        ...,
        description="General, industry-agnostic explanation of why this information matters for building a marketing strategy."
    )
    status: RequirementStatus = Field(
        default=RequirementStatus.UNKNOWN,
        description="Current status of the requirement (UNKNOWN, KNOWN, or UNAVAILABLE)."
    )
    value: Optional[Any] = Field(
        default=None,
        description="The collected answer or information value if status is KNOWN."
    )
    is_must_have: bool = Field(
        default=False,
        description="True if this requirement should generally be resolved (KNOWN or UNAVAILABLE) before strategy generation."
    )
    is_custom: bool = Field(
        default=False,
        description="True if dynamically generated by the LLM during conversation rather than coming from the base framework."
    )
