import re
from enum import Enum
from typing import Any, List, Optional
from pydantic import BaseModel, Field


class RequirementStatus(str, Enum):
    """
    Status of an information requirement during the collection process.
    - UNKNOWN: Information not yet collected or evaluated.
    - KNOWN: Information has been provided and stored.
    - UNAVAILABLE: Applicable, but the answer isn't known or decided yet (e.g., "we don't have a fixed budget yet").
    - NOT_RELEVANT: Not applicable to this specific business at all (e.g., "pricing model" does not apply to a donation-based non-profit).
    """
    UNKNOWN = "UNKNOWN"
    KNOWN = "KNOWN"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_RELEVANT = "NOT_RELEVANT"


class InformationRequirement(BaseModel):
    """
    Represents a single piece of marketing information required or evaluated by the agent.
    Industry-agnostic schema supporting both predefined base framework items and dynamically discovered requirements.
    """
    id: str = Field(
        ...,
        description="Short unique string identifier for the requirement (e.g., 'pricing_model' or 'dynamic_cuisine_type')."
    )
    title: str = Field(
        ...,
        description="Short human-readable title of the requirement (e.g., 'Pricing Model')."
    )
    description: str = Field(
        ...,
        description="General, industry-agnostic explanation of why this information matters for building a marketing strategy."
    )
    status: RequirementStatus = Field(
        default=RequirementStatus.UNKNOWN,
        description="Current status of the requirement (UNKNOWN, KNOWN, UNAVAILABLE, or NOT_RELEVANT)."
    )
    value: Optional[Any] = Field(
        default=None,
        description="The collected answer or information value if status is KNOWN."
    )
    is_must_have: bool = Field(
        default=False,
        description="True if this requirement should generally be resolved (KNOWN or UNAVAILABLE) before strategy generation."
    )
    is_custom: bool = Field(
        default=False,
        description="True if dynamically generated by the LLM during conversation rather than coming from the base framework."
    )


def create_dynamic_requirement(
    raw_id: str,
    title: str,
    description: str,
    is_must_have: bool = True
) -> InformationRequirement:
    """
    Creates a validated dynamic InformationRequirement with a collision-safe ID starting with 'dynamic_'.
    Sets is_custom=True and status=UNKNOWN.
    """
    clean_name = raw_id.strip().lower()
    clean_name = re.sub(r'[^a-z0-9_]', '_', clean_name)
    clean_name = re.sub(r'_+', '_', clean_name).strip('_')
    
    if not clean_name.startswith("dynamic_"):
        clean_id = f"dynamic_{clean_name}"
    else:
        clean_id = clean_name

    return InformationRequirement(
        id=clean_id,
        title=title.strip(),
        description=description.strip(),
        status=RequirementStatus.UNKNOWN,
        value=None,
        is_must_have=is_must_have,
        is_custom=True,
    )


def is_duplicate_requirement(
    req_id: str,
    title: str,
    existing_requirements: List[InformationRequirement]
) -> bool:
    """
    Checks if a requirement ID or title semantically collides with any requirement in existing_requirements.
    """
    clean_id = req_id.strip().lower()
    clean_title = title.strip().lower()

    for r in existing_requirements:
        if r.id.lower() == clean_id:
            return True
        if r.title.lower() == clean_title:
            return True
        if clean_id.startswith("dynamic_") and clean_id[8:] == r.id.lower():
            return True

    return False

