"""
SQLAlchemy ORM model for the information_requirements table.

Stores dynamic information requirements identified for a specific conversation.
Uses a composite primary key: (conversation_id, requirement_id).
"""

import uuid
from datetime import datetime
from typing import Any, Optional, TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base

if TYPE_CHECKING:
    from .conversation import Conversation


class InformationRequirement(Base):
    """
    ORM model for the information_requirements table.

    Tracks requirement resolution status (UNKNOWN, KNOWN, UNAVAILABLE, NOT_RELEVANT)
    and collected values for a conversation.
    """

    __tablename__ = "information_requirements"

    # ---------------------------------------------------------------------------
    # Composite Primary Key fields
    # ---------------------------------------------------------------------------
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("conversations.id", ondelete="CASCADE"),
        primary_key=True,
        nullable=False,
        index=True,
        comment="Foreign key to conversations. Part 1 of composite primary key.",
    )

    requirement_id: Mapped[str] = mapped_column(
        String(255),
        primary_key=True,
        nullable=False,
        comment="Requirement identifier string (e.g. 'usp_differentiation'). Part 2 of composite PK.",
    )

    # ---------------------------------------------------------------------------
    # Content & status fields
    # ---------------------------------------------------------------------------
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Short human-readable title of the requirement.",
    )

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="General description of why this requirement matters.",
    )

    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="UNKNOWN",
        comment="Requirement status. Expected: UNKNOWN, KNOWN, UNAVAILABLE, NOT_RELEVANT.",
    )

    value: Mapped[Optional[Any]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Collected answer / value stored as JSONB.",
    )

    is_must_have: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="True if requirement should generally be resolved before strategy generation.",
    )

    is_custom: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="True if dynamically generated by LLM during conversation.",
    )

    # ---------------------------------------------------------------------------
    # Timestamps (timezone-aware)
    # ---------------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when requirement reached a resolved status (KNOWN, UNAVAILABLE, etc).",
    )

    # ---------------------------------------------------------------------------
    # Relationship — back-reference to parent Conversation
    # ---------------------------------------------------------------------------
    conversation: Mapped["Conversation"] = relationship(
        "Conversation",
        back_populates="information_requirements",
    )

    def __repr__(self) -> str:
        return (
            f"<InformationRequirement conv_id={self.conversation_id!s} "
            f"req_id={self.requirement_id!r} status={self.status!r}>"
        )
