"""initial database schema

Revision ID: 6eb3b9045c09
Revises:
Create Date: 2026-10-08 11:31:31.747753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eb3b9045c09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Lifecycle status of the request. Allowed values: in_progress, completed, failed, cancelled.'),
    sa.Column('current_stage', sa.String(length=100), nullable=True, comment='Current processing stage. Examples: initial_form, online_presence, requirement_analysis, dynamic_questions, strategy_generation, completed.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_request_id', sa.UUID(), nullable=False, comment='Foreign key to strategy_requests. Unique — enforces 1-to-1 relationship.'),
    sa.Column('company_name', sa.String(length=1000), nullable=False, comment='Name or description of the business or company. Max 1000 chars.'),
    sa.Column('product_or_service', sa.String(length=750), nullable=False, comment='Primary product or service offered by the business. Max 750 chars.'),
    sa.Column('marketing_goal', sa.String(length=500), nullable=False, comment='Primary marketing goal or objective. Max 500 chars.'),
    sa.Column('target_audience', sa.String(length=750), nullable=False, comment='Target audience or ideal customer profile. Max 750 chars.'),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Marketing budget amount as a decimal. Must be > 0 when provided.'),
    sa.Column('budget_currency', sa.String(length=10), nullable=True, comment='ISO currency code for budget_amount. Expected values: INR or USD.'),
    sa.Column('current_marketing_channels', sa.String(length=500), nullable=True, comment='Channels currently in use (e.g. Instagram, Google Ads). Max 500 chars.'),
    sa.Column('website_social_links', sa.Text(), nullable=True, comment='Website or social media links provided by the user. Max 2000 chars.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_request_id'], ['strategy_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_request_id', name='uq_businesses_strategy_request_id')
    )
    op.create_index(op.f('ix_businesses_strategy_request_id'), 'businesses', ['strategy_request_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key, also serves as the LangGraph thread_id.'),
    sa.Column('strategy_request_id', sa.UUID(), nullable=False, comment='Foreign key to strategy_requests. Unique — enforces 1-to-1 relationship.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status of the conversation. Expected: waiting_for_reply, completed, failed.'),
    sa.Column('current_requirement_id', sa.String(length=255), nullable=True, comment='ID of the requirement currently being asked (string, non-FK).'),
    sa.Column('is_sufficient', sa.Boolean(), nullable=False, comment='True if information gathered is sufficient to generate strategy.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_request_id'], ['strategy_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_request_id', name='uq_conversations_strategy_request_id')
    )
    op.create_index(op.f('ix_conversations_strategy_request_id'), 'conversations', ['strategy_request_id'], unique=False)
    op.create_table('online_presence_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_request_id', sa.UUID(), nullable=False, comment='Foreign key to strategy_requests.'),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='Platform type. Expected values: website, instagram, facebook, linkedin.'),
    sa.Column('original_url', sa.Text(), nullable=False, comment='Original URL submitted by user.'),
    sa.Column('normalized_url', sa.Text(), nullable=True, comment='Normalized URL after validation.'),
    sa.Column('scrape_status', sa.String(length=50), nullable=False, comment='Scrape status. Expected values: success, failed, skipped, pending.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if scraping failed.'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Extracted strategy summary from the source.'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured source-specific scraped details.'),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when scraping completed.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_request_id'], ['strategy_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_request_id', 'platform', name='uq_online_presence_sources_request_platform')
    )
    op.create_index(op.f('ix_online_presence_sources_strategy_request_id'), 'online_presence_sources', ['strategy_request_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Foreign key to conversations.id.'),
    sa.Column('sender', sa.String(length=50), nullable=False, comment='Sender of the message. Expected: user, agent.'),
    sa.Column('message_type', sa.String(length=50), nullable=True, comment='Type/category of message (e.g. greeting, question, answer, system, completion).'),
    sa.Column('requirement_id', sa.String(length=255), nullable=True, comment='Non-FK reference to requirement_id associated with this message.'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full message text content.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index('ix_chat_messages_conversation_id_id', 'chat_messages', ['conversation_id', 'id'], unique=False)
    op.create_table('information_requirements',
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Foreign key to conversations. Part 1 of composite primary key.'),
    sa.Column('requirement_id', sa.String(length=255), nullable=False, comment="Requirement identifier string (e.g. 'usp_differentiation'). Part 2 of composite PK."),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short human-readable title of the requirement.'),
    sa.Column('description', sa.Text(), nullable=True, comment='General description of why this requirement matters.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Requirement status. Expected: UNKNOWN, KNOWN, UNAVAILABLE, NOT_RELEVANT.'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Collected answer / value stored as JSONB.'),
    sa.Column('is_must_have', sa.Boolean(), nullable=False, comment='True if requirement should generally be resolved before strategy generation.'),
    sa.Column('is_custom', sa.Boolean(), nullable=False, comment='True if dynamically generated by LLM during conversation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when requirement reached a resolved status (KNOWN, UNAVAILABLE, etc).'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'requirement_id')
    )
    op.create_index(op.f('ix_information_requirements_conversation_id'), 'information_requirements', ['conversation_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_request_id', sa.UUID(), nullable=False, comment='Foreign key to strategy_requests.id.'),
    sa.Column('conversation_id', sa.UUID(), nullable=True, comment='Optional foreign key to conversations.id.'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='Name/identifier of LLM model used (e.g. gpt-4o-mini).'),
    sa.Column('operation', sa.String(length=100), nullable=False, comment='Operation name (e.g. relevance_analysis, question_generation, strategy_generation).'),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Number of prompt/input tokens.'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Number of completion/output tokens.'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Total tokens consumed.'),
    sa.Column('input_cost', sa.Numeric(precision=12, scale=6), nullable=True, comment='Calculated input cost.'),
    sa.Column('output_cost', sa.Numeric(precision=12, scale=6), nullable=True, comment='Calculated output cost.'),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=6), nullable=True, comment='Total calculated call cost.'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Call execution duration in milliseconds.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Execution status. Expected: success, failed.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if the LLM call failed.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_request_id'], ['strategy_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_conversation_id'), 'llm_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_strategy_request_id'), 'llm_usage', ['strategy_request_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Foreign key to conversations.id.'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number of the generated strategy for this conversation.'),
    sa.Column('strategy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete generated MarketingStrategy structure as JSONB.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'version', name='uq_strategies_conversation_id_version')
    )
    op.create_index(op.f('ix_strategies_conversation_id'), 'strategies', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_conversation_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_llm_usage_strategy_request_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_conversation_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_information_requirements_conversation_id'), table_name='information_requirements')
    op.drop_table('information_requirements')
    op.drop_index('ix_chat_messages_conversation_id_id', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_online_presence_sources_strategy_request_id'), table_name='online_presence_sources')
    op.drop_table('online_presence_sources')
    op.drop_index(op.f('ix_conversations_strategy_request_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_businesses_strategy_request_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('strategy_requests')
    # ### end Alembic commands ###
